Started the project and modified the README and .gitignore
tkz96/My-Portfolio-Website pull request #1
Opened 2022-02-10 10:35 UTC by tkz96

2022-02-10 23:56 UTC, Hamzaoutdoors requested changes
Hey <STUDENT NAME>, I am **Hamza** your reviewer for this PR 😸 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![image](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## To Highlight
✔️ The repo looks professional
✔️ Git/GitHub flow best practices have been followed
✔️ There are no linter errors
✔️ You have a descriptive README

## Required Changes ♻️

_See the inline comments below for more required changes 😃_  

- [ ] Please, Write a meaningful title for your pull request and always add a short summary of changes introduced in the pull request. you can check the [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
**N.A**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-10 23:56 UTC, Hamzaoutdoors commented on index.html
> +        <p class="logo-placeholder">Welcome!</p>
- [ ] As you can see clearly in almost websites the `logo` should be a button to navigate to the home page (index.html), Kindly wrap your logo in an  anchor element (`a` tag)

2022-02-10 23:56 UTC, Hamzaoutdoors commented on index.html
> +            <h2>I am Talha.<br>Glad to see you!</h2>
- [ ] Kindly use the `h1` tag here, that will make your code more semantic and structured

2022-02-11 09:54 UTC, gemmen29 approved these changes
Hi @tkz96, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions
- Please give the branch a meaningful name like the name of the project `setup-and-mobile-skeleton`, not `project-build-1`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-11 10:34 UTC, tkz96 commented
Understood. I will take care of naming the branches.

2022-02-11 10:34 UTC, merged