Added majority of the markup including all the sections: portfolio-ca…
tkz96/My-Portfolio-Website pull request #2
Opened 2022-02-11 14:06 UTC by tkz96

…rds, about-myself, languages, contact-form. Fixed some CSS errors

2022-02-11 22:57 UTC, RolandM99 requested changes
Hello @tkz96 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media0.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif)

### To highlight 💯 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Rolandm99 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-11 22:57 UTC, RolandM99 commented on index.html
> +            <div class="icons">
- [ ] the sentence **LET'S CONNECT** should use the header `hx` tag(h1, h2, h3,...). Kindly replace the `p` tag by a header ` hx` tag .

2022-02-11 22:57 UTC, RolandM99 commented on index.html
> +            <li class="skills">Skills</li>
- [ ] Kindly, Make sure that your design looks similar to the design in the [Figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
The technology categories should look like this : 
FIGMA DESIGN 👍 
![image](https://user-images.githubusercontent.com/71874425/153680126-ad9cf8ca-a056-49d1-bffb-79c1d992ead7.png)
YOUR DESIGN 👎 

![image](https://user-images.githubusercontent.com/71874425/153680294-8b5d5d5c-a947-484a-80a6-a9d0b2aab29d.png)
- [ ] Please, kindly fix this to meet the Figma design provided

2022-02-11 22:57 UTC, RolandM99 commented on styles.css
> +  border-radius: 8px;
- [ ] Please, Add the button styling (Hover, enable, Active, Pressed ) for all your buttons implemented referencing to the Figma template.
Figma buttons styling :
![image](https://user-images.githubusercontent.com/71874425/153681023-88a1eda3-85ac-40b2-b9bb-227feaa059ff.png)

2022-02-12 15:13 UTC, Hamzaoutdoors approved these changes
Hi @tkz96, 

## Congratulations! 🎉 Project Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚀

To Highlight:

- [x] The Pull Request has a proper title and description. ✔️
- [x] You have added a descriptive Readme file. Good Job. ✔️
- [x] There is no linter error is present. ✔️
- [x] Project has met all the technical aspects you needed for this project! ✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] It will be better to regroup all assets (icons, background images) in a folder you can call it `assets`, which will make your code cleaner.

_Cheers and Happy coding and Keep rocking!_ 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-12 15:17 UTC, tkz96 commented
Thank you so much for the review @RolandM99 @Hamzaoutdoors 

I will try my best to improve and use best pratices

2022-02-12 15:17 UTC, merged